"$schema" = 'https://starship.rs/config-schema.json'

palette = 'catppuccin_latte'

format = """
$username\
[](fg:bg bg:flamingo)\
$hostname\
[](fg:flamingo bg:mauve)\
$directory\
[](fg:mauve bg:peach)\
$git_branch\
$git_status\
[](fg:peach bg:maroon)\
$status\
[](fg:maroon bg:yellow)\
$cmd_duration\
[](fg:yellow bg:bg)\
$fill\
$time\
$line_break\
$character\
"""

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
rosewater_light = "#f5e0dc"
flamingo = "#dd7878"
flamingo_light = "#f2cdcd"
pink = "#ea76cb"
pink_light = "#f5c2e7"
orange = "#cba6f7"
mauve = "#8839ef"
mauve_light = "#cba6f7"
red = "#d20f39"
red_light = "#f38ba8"
maroon = "#e64553"
maroon_light = "#eba0ac"
peach = "#fe640b"
peach_light = "#fab387"
yellow = "#df8e1d"
yellow_light = "#f9e2af"
green = "#40a02b"
green_light = "#a6e3a1"
teal = "#179299"
teal_light = "#94e2d5"
sky = "#04a5e5"
sky_light = "#89dceb"
sapphire = "#209fb5"
sapphire_light = "#74c7ec"
blue = "#1e66f5"
blue_light = "#89b4fa"
lavender = "#7287fd"
lavender_light = "#b4befe"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
mantle_light = "#181825"
crust = "#dce0e8"
bg = "#181825"

[username]
show_always = true
format = "[ 󰊠](fg:text bg:bg)[ $user ](fg:text bg:bg)"

[hostname]
ssh_only = false
format = "[ ](fg:flamingo_light bg:flamingo)[ $ssh_symbol$hostname ](fg:flamingo_light bg:flamingo)"

[directory]
format = "[ ](fg:mauve_light bg:mauve)[ $path ](fg:mauve_light bg:mauve)"
truncate_to_repo = false
truncation_length = 0

[git_branch]
format = "[ ](fg:peach_light bg:peach)[ $branch(:$remote_branch )](fg:peach_light bg:peach)"

[git_status]
diverged = '[󰃻 +$ahead_count -$behind_count](fg:red) '
ahead = '⇡$count '
behind = '⇣$count '
up_to_date = ' 󰾨 '
conflicted = ' 󰈻 '
stashed = ' $count '
modified = '$count! '
untracked = '$count? '
staged = '+$count '
deleted = '-$count '
renamed = '±$count '
format = "[$ahead_behind $conflicted$stashed$modified$untracked$staged$deleted$renamed](fg:peach_light bg:peach)"

[status]
format = "[ ](fg:maroon_light bg:maroon)[ $status ](fg:maroon_light bg:maroon)"
disabled = false

[cmd_duration]
format = "[ 󱐋](fg:yellow_light bg:yellow)[ $duration ](fg:yellow_light bg:yellow)"
min_time = 100
show_milliseconds = true

[fill]
symbol = ' '
style = 'bg:bg'

[time]
time_format = "󰥔 %a %b %e, %I:%M:%S %p"
format = "[ $time](fg:text bg:bg)"
disabled = false

[character]
success_symbol = " [](fg:#a6d189)"
error_symbol = " [](fg:#ea999c)"

# [conda]
# symbol = ' '
# style = 'bold green'
# format = '[$symbol$environment]($style) '

# [python]
# symbol = ' '
# style = 'bold green'
# format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

# [ruby]
# symbol = ' '
# style = 'bold green'
# format = '[$symbol($version )]($style)'

# [nodejs]
# symbol = '󰎙 '
# style = 'bold green'
# format = '[$symbol($version )]($style)'
