"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

palette = 'catppuccin_latte'

format = """
$status\
$directory\
$cmd_duration\
$line_break\
$character\
"""

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
orange = "#cba6f7"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[status]
format = "[─](fg:separator)[](fg:status)[](fg:icon bg:status)[](fg:status bg:background)[ $status](bg:background)[](fg:background)"
pipestatus = true
pipestatus_separator = "-"
pipestatus_segment_format = "$status"
pipestatus_format = "[─](fg:separator)[](fg:status)[](fg:icon bg:status)[](fg:status bg:background)[ $pipestatus](bg:background)[](fg:background)"
disabled = false

[directory]
format = "[─](fg:separator)[](fg:mauve)[](fg:text bg:mauve)[](fg:mauve bg:overlay2)[ $path](bg:overlay2)[](fg:overlay2)"
truncate_to_repo = false
truncation_length = 0

[character]
success_symbol = " [\uf155](fg:prompt_ok)"
error_symbol = " [\uf155](fg:prompt_err)"

[cmd_duration]
format = "[─](fg:separator)[](fg:duration)[󱐋](fg:icon bg:duration)[](fg:duration bg:background)[ $duration](bg:background)[](fg:background)"
min_time = 1000

[time]
format = "[](fg:duration)[󰥔](fg:icon bg:duration)[](fg:duration bg:background)[ $time](bg:background)[](fg:background)"
disabled = false

# format = """
# [](surface0)\
# $username\
# [@](bg:surface0 fg:text)\
# $hostname\
# [](bg:peach fg:surface0)\
# $conda\
# $python\
# $ruby\
# $nodejs\
# $time\
# [ ](fg:peach)\
# $directory$git_branch$git_status$cmd_duration
# $character"""

# palette = 'catppuccin_mocha'

# [palettes.catppuccin_mocha]
# rosewater = "#f5e0dc"
# flamingo = "#f2cdcd"
# pink = "#f5c2e7"
# orange = "#cba6f7"
# red = "#f38ba8"
# maroon = "#eba0ac"
# peach = "#fab387"
# yellow = "#f9e2af"
# green = "#a6e3a1"
# teal = "#94e2d5"
# sky = "#89dceb"
# sapphire = "#74c7ec"
# blue = "#89b4fa"
# lavender = "#b4befe"
# text = "#cdd6f4"
# subtext1 = "#bac2de"
# subtext0 = "#a6adc8"
# overlay2 = "#9399b2"
# overlay1 = "#7f849c"
# overlay0 = "#6c7086"
# surface2 = "#585b70"
# surface1 = "#45475a"
# surface0 = "#313244"
# base = "#1e1e2e"
# mantle = "#181825"
# crust = "#11111b"

# [username]
# style_user = "bg:surface0 fg:text"
# style_root = "bg:surface0 fg:text"
# show_always = true
# format = "[$user]($style)"

# [hostname]
# ssh_only = false
# style = "bg:surface0 fg:text"
# format = "[$ssh_symbol$hostname ]($style)"

# [time]
# disabled = false
# style = "fg:mantle bg:peach"
# time_format = "%I:%M"
# format = '[[  $time ](fg:mantle bg:peach)]($style)'

# [directory]
# style = "white"

# [character]
# success_symbol = " [\uf0da](green)"
# error_symbol = "[ 󰟢](red)"

# [git_branch]
# symbol = ' '
# style = 'bold purple'
# format = '[$symbol$branch(:$remote_branch)]($style) '

# [git_status]
# diverged = '[󰃻 +$ahead_count -$behind_count](bold red) '
# ahead = '⇡$count '
# behind = '⇣$count '
# up_to_date = '󰾨 '
# conflicted = '󰈻 '
# stashed = ' $count '
# modified = '!$count '
# untracked = '[?$count](bold #FFC0CB) '
# staged = '[+$count](bold green) '
# deleted = '[-$count](bold red) '
# renamed = '[±$count](bold yellow) '
# style = 'bold purple'
# format = '[$ahead_behind $conflicted$stashed$modified$untracked$staged$deleted$renamed]($style) '

# [cmd_duration]
# min_time = 1000
# show_milliseconds = true

# [conda]
# symbol = ' '
# style = 'bold green'
# format = '[$symbol$environment]($style) '

# [python]
# symbol = ' '
# style = 'bold green'
# format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

# [ruby]
# symbol = ' '
# style = 'bold green'
# format = '[$symbol($version )]($style)'

# [nodejs]
# symbol = '󰎙 '
# style = 'bold green'
# format = '[$symbol($version )]($style)'
