"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
[](surface0)\
$username\
[@](bg:surface0 fg:text)\
$hostname\
[](bg:peach fg:surface0)\
$conda\
$python\
$ruby\
$nodejs\
$time\
[ ](fg:peach)\
$directory$git_branch$git_status$cmd_duration
$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[username]
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
show_always = true
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bg:surface0 fg:text"
format = "[$ssh_symbol$hostname ]($style)"

[time]
disabled = false
style = "fg:mantle bg:peach"
time_format = "%I:%M"
format = '[[  $time ](fg:mantle bg:peach)]($style)'

[directory]
style = "white"

[character]
success_symbol = " [\uf0da](green)"
error_symbol = "[ 󰟢](red)"

[git_branch]
symbol = ' '
style = 'bold purple'
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
diverged = '[󰃻 +$ahead_count -$behind_count](bold red) '
ahead = '⇡$count '
behind = '⇣$count '
up_to_date = '󰾨 '
conflicted = '󰈻 '
stashed = ' $count '
modified = '!$count '
untracked = '[?$count](bold #FFC0CB) '
staged = '[+$count](bold green) '
deleted = '[-$count](bold red) '
renamed = '[±$count](bold yellow) '
style = 'bold purple'
format = '[$ahead_behind $conflicted$stashed$modified$untracked$staged$deleted$renamed]($style) '

[cmd_duration]
min_time = 1000
show_milliseconds = true

[conda]
symbol = ' '
style = 'bold green'
format = '[$symbol$environment]($style) '

[python]
symbol = ' '
style = 'bold green'
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[ruby]
symbol = ' '
style = 'bold green'
format = '[$symbol($version )]($style)'

[nodejs]
symbol = '󰎙 '
style = 'bold green'
format = '[$symbol($version )]($style)'
