"$schema" = 'https://starship.rs/config-schema.json'

palette = 'hardcore'

format = """
$git_branch$git_status\
$nodejs\
$status\
$cmd_duration\
$line_break\
$directory\
$character\
"""

# https://gogh-co.github.io/Gogh/
[palettes.hardcore]
success = "#a6e22e"
error = "#f92672"
separator = "#333333"
username = "#a6e22e"
hostname = "#a6e22e"
directory = "#999999"
git = "#666666"
environment = "#444444"
cmd_duration = "#fd971f"

# [username]
# show_always = true
# format = "[$user](fg:username)[@](fg:separator)"

# [hostname]
# ssh_only = false
# format = "[$ssh_symbol$hostname](fg:hostname) "

# https://starship.rs/config/#git-branch
[git_branch]
format = "[](fg:git)[ $branch(:$remote_branch )](fg:git) "

# https://starship.rs/config/#git-status
[git_status]
diverged = '󰃻 +$ahead_count -$behind_count '
ahead = '⇡ $count '
behind = '⇣ $count '
# up_to_date = '󰾨 '
conflicted = '󰈻 '
stashed = ' $count '
modified = '$count! '
untracked = '$count? '
staged = '+$count '
deleted = '-$count '
renamed = '±$count '
format = "[$ahead_behind$conflicted$stashed$modified$untracked$staged$deleted$renamed](fg:git)"

# https://starship.rs/config/#node-js
[nodejs]
format = '[󰎙 ](fg:environment)[$version](fg:environment) '

# https://starship.rs/config/#status
[status]
format = "[ ](fg:error)[$status](fg:error) "
disabled = false

# https://starship.rs/config/#command-duration
[cmd_duration]
format = "[󱐋 ](fg:cmd_duration)[$duration](fg:cmd_duration) "
min_time = 100
show_milliseconds = true

# https://starship.rs/config/#directory
[directory]
format = "[$path](fg:directory)"
truncate_to_repo = true
truncation_length = 2

# https://starship.rs/config/#character
[character]
success_symbol = "[](fg:success)"
error_symbol = "[](fg:error)"
